{% set version = "1.3.8-4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-timsac
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/timsac_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/timsac/timsac_{{ version }}.tar.gz
  sha256: 53ce2658286e18472110444d4157136ab7aa95661b2a7a24c8ea91103eb3b83e

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('timsac')"           # [not win]
    - "\"%R%\" -e \"library('timsac')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=timsac
  license: GPL-2.0-or-later
  summary: Functions for statistical analysis, prediction and control of time series based mainly on Akaike and Nakagawa (1988) <ISBN 978-90-277-2786-2>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr

# Package: timsac
# Version: 1.3.6
# Title: Time Series Analysis and Control Package
# Author: The Institute of Statistical Mathematics
# Maintainer: Masami Saga <msaga@mtb.biglobe.ne.jp>
# Depends: R (>= 3.0.0)
# Imports: graphics, grDevices, stats
# Description: Functions for statistical analysis, prediction and control of time series based mainly on Akaike and Nakagawa (1988) <ISBN 978-90-277-2786-2>.
# License: GPL (>= 2)
# MailingList: Please send bug reports to ismrp@jasp.ism.ac.jp.
# NeedsCompilation: yes
# Packaged: 2018-03-06 07:35:07 UTC; msaga
# Repository: CRAN
# Date/Publication: 2018-03-06 15:54:00 UTC
