{% set version = '1.3.5' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-timsac
  version: {{ version|replace("-", "_") }}

source:
  fn: timsac_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/timsac_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/timsac/timsac_{{ version }}.tar.gz

  sha256: 4052135ffe0dd49b67385c9fe123586acef930f07a8829015fd095847fe44edc

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('timsac')"  # [not win]
    - "\"%R%\" -e \"library('timsac')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=timsac
  license: GPL (>= 2)
  summary: Functions for statistical analysis, prediction and control of time series.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]
extra:
   recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - Johanneskoester
    - Bgruening
    - Daler
    - Jdblischak
