travis:
  secure:
    BINSTAR_TOKEN: lDI6esibygC+rEjNanzWLQL1QqPf48LQUfcuhm2gaxIpia96gcXSonRzEtVwJoEPPXwKO+TBse0wL+LI0LhEaHYIWTDddJk2oNbBCkzAtSes6XjO6HjXN/84pvqpzUWP0Mxsi3Oe3/aC9nezyeJIjpUKKeo3VKySGVqU+uSVbTZmbc5zTzl0txA+RzE2fflVIyDVLJlSnlGh2cGaiW0DeiGyAU7jHJ3LqWVz59IdP/UcB66wvk8r9j7FI5AO7YnBxNlNJd2K4eCsxgOI2hose3eGbPUJAgDy6KHMf/V7HST8McueSKaNb+92bYRCaPVjOp0yOxCs2Tngg4fInBvIl//zb1RVZ9iUMFXb/nUMum1rVv+rAffjR9pByL8S8IORWGcW7Yn8Q5Bpny7BcQR6iMnzw0JQsMc4kHTAx8RAyIDHTe6MXNCK691Ijwwkj1SzFP/yuMA0OSahsktOxyuAls4u7RPckXDKGq6TKN8WlYQsMsGgYYaSFtN96OYFPVp+2ZRI9oAdCw4dt6IrOdblyinQCoOeyF31KbElGObQXlt7FZe/yW/U+2s/RGwXchzRvY8sjWLhPrIf04uzWxdfs46/5q8JVrKwA5MaXQTxYjUNyZFUogL8sxvZH8MYm9DOPFdzhMHdpM+KLJfNRZTAMVtIM8EQPVgY6KDjPvAUydI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
